# Copyright 2022 Datum Technology Corporation
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
########################################################################################################################


[project]
name        = "uvml_mem"
full-name   = "Moore.io Memory Modeling Library"
description = ""

[simulation]
preferred-simulators = [ "vivado" ]
